spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:classpath:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 9000
  servlet:
    context-path: /
    session:
      timeout: 10m

logging:
  level:
    com.test.book: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.session.web.http: debug
    org.springframework.web: info
